# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: soatestcli -config "user://Example Configuration" -settings "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.1\soatestcli.properties" -data %cd%
  displayName: 'soatest'

- task: PublishParasoftTestResults@1
  inputs:
    testRunner: 'XTest10x'
    testResultsFiles: '**/*.xml'
    testResultsFormat: 'JUnit'
